HealthKitTask Documentation Update
carekit-apple/CareKit pull request #578
Opened 2021-04-27 17:49 UTC by npsantini

Updated title description in health kit task documentation.

2021-04-28 17:34 UTC, gavirawson-apple requested changes
Thanks for the fix!

2021-04-28 17:34 UTC, gavirawson-apple commented on CareKitStore/CareKitStore/HealthKit/OCKHealthKitTask.swift
> +    ///   - title: A title that will be used to represent this health kit task to the patient.
```suggestion
    ///   - title: A title that will be used to represent this HealthKit task to the patient.
```

2021-05-05 23:19 UTC, erik-apple approved these changes

2021-05-06 00:59 UTC, gavirawson-apple approved these changes

2021-05-06 14:35 UTC, merged