feat: Update OCKSurveyTaskViewController to support ResearchKit 3.0
carekit-apple/CareKit pull request #711
Opened 2024-02-29 01:15 UTC by cbaker6

2024-03-01 19:23 UTC, cbaker6 commented
If https://github.com/ResearchKit/ResearchKit/pull/1566 is accepted, we can revert this back to https://github.com/carekit-apple/CareKit/commit/d1a87996001487789f13cdc3d9bd68101f5a8b28

2024-03-06 07:49 UTC, ronzilla-apple commented on CareKit/CareKit/iOS/Task/View Controllers/OCKSurveyTaskViewController.swift
> +#endif
Would it be possible to change the entire diff to something like

```suggestion
#if canImport(ResearchKitUI)
import ResearchKitUI
public typealias ORKTaskViewControllerFinishReason = ORKTaskFinishReason
#endif
```

2024-03-06 07:53 UTC, ronzilla-apple requested changes
I was able to get a sample project building with only the conditional import and the typealias.
That change worked with both RK3.0 and RK2.x

2024-03-18 23:35 UTC, gavirawson-apple approved these changes

2024-03-28 16:13 UTC, merged

2024-03-28 16:13 UTC, gavirawson-apple commented
Thanks for the fix Corey!