feat: Allow developers to create instances of LinearCareTaskProgress
carekit-apple/CareKit pull request #713
Opened 2024-05-23 18:36 UTC by cbaker6

Making the initializer public allows developers create linear progress, similar to

2024-05-29 23:57 UTC, gavirawson-apple commented
Hey Corey, do you have a use case in mind where it's useful to create these progress structs manually? At the moment, the entry point is a helper method on a CareKit event:

```swift
// Existing entry point
let progress = event.computeProgress(by: .checkingOutcomeExists)

// Internal entry point. In what scenarios is this useful as public API?
let progress = BinaryCareTaskProgress(isCompleted: true)
```

2024-05-30 00:30 UTC, cbaker6 commented
Hey @gavirawson-apple, I don't necessarily have a use case for `BinaryCareTaskProgress` and can get away with using `event.computeProgress(by: .checkingOutcomeExists)` as you mentioned.

When it comes to `LinearCareTaskProgress`, I was attempting to convert code in one of our apps from the previous version of CareKit that used custom `OCKEventAggregator`'s to compute the mean and median progress. For the conversion, I was attempting to take advantage of creating `LinearCareTaskProgress`. Currently, I created I copied/pasted `LinearCareTaskProgress` and renamed it `TempLinearCareTaskProgress` to be able to create instances.

This allows me to do something like:

```swift
extension CareTaskProgressStrategy {

    static func computeProgressByCalculatingMeanOutcomeValues(for event: OCKAnyEvent) -> TempLinearCareTaskProgress {

        let outcomeValues = event.outcome?.values ?? []

            let numberOfCompletedOutcomes = Double(outcomeValues.count)
            let summedOutcomesValue = outcomeValues
                .map(accumulableDoubleValue)
                .reduce(0, +)

            let targetValues = event.scheduleEvent.element.targetValues

            let summedTargetValue = targetValues
                .map(accumulableDoubleValue)
                .reduce(nil) { partialResult, nextTarget -> Double? in
                    return sum(partialResult, nextTarget)
                }

            if numberOfCompletedOutcomes == 0 {
                return TempLinearCareTaskProgress(value: 0, goal: summedTargetValue)
            } else {
                let mean = summedOutcomesValue / numberOfCompletedOutcomes
                return TempLinearCareTaskProgress(value: summedOutcomesValue, goal: summedTargetValue)
            }
    }
}
```

Let me know if you suggest I approach this differently.

2024-05-31 16:36 UTC, gavirawson-apple commented
Thanks for the snippet, seems worthwhile to open the initializer up if it's helpful. The original thinking was that clients can create a custom struct that conforms to `CareTaskProgress` rather than using the ones in the framework, but filling out `fractionCompleted` probably isn't always trivial. Let's do it.

2024-05-31 16:45 UTC, gavirawson-apple requested changes
Looks great, I've just suggested some changes to the documentation - we can pull in the language from the existing documentation in the structs to make sure we're using consistent language.

2024-05-31 16:45 UTC, gavirawson-apple commented on CareKitStore/CareKitStore/TaskProgress/BinaryCareTaskProgress.swift
> +    ///   - isCompleted: The user progress for a task is either completed or incomplete.
```suggestion
    /// Create user progress for a task that is either completed or incomplete.
    ///
    /// - Parameters:
    ///   - isCompleted: True if the task is considered completed.
```

2024-05-31 16:45 UTC, gavirawson-apple commented on CareKitStore/CareKitStore/TaskProgress/LinearCareTaskProgress.swift
> +    /// the progress value is greater than zero.
```suggestion
    /// Create a structure that defines user progress for a task that can be completed over time.
    /// 
    /// - Parameters: 
    ///   - value: The progress that's been made towards reaching the goal.
    ///   - goal: A value that indicates whether the task is complete. When there is no goal, the value is `nil`.  The task is considered completed if the progress value is greater than zero.
```

2024-05-31 17:01 UTC, cbaker6 commented
> The original thinking was that clients can create a custom struct that conforms to CareTaskProgress rather than using the ones in the framework, but filling out fractionCompleted probably isn't always trivial

In addition, developers will need to create an instance of `LinearCareTaskProgress` for creating `OCKDataSeriesConfiguration` and `OCKCartesianChartViewController`, though this probably won't be needed when switching to Swift Charts: https://github.com/carekit-apple/CareKit/blob/fbdfa3a14ad9a002b67e8484f344e92f2581629b/CareKit/CareKit/iOS/Chart/View%20Controllers/OCKDataSeriesConfiguration.swift#L84-L110

2024-06-11 17:21 UTC, gavirawson-apple commented
@coreybaker-apple I see there are some failing tests here. Are tests passing locally for you?

2024-06-11 17:21 UTC, gavirawson-apple commented
@cbaker6 I see there are some failing tests on CI. Are tests passing locally for you?

2024-06-11 22:41 UTC, cbaker6 commented
Hey @gavirawson-apple I've run all of the test locally and they pass. I haven't been able to replicate the failures the CI finds

2024-06-12 16:05 UTC, gavirawson-apple commented
Gotcha, passes locally for me too so it looks good to go. We can merge the PR and I'll make a note to look into the CI issues.

2024-06-12 16:05 UTC, merged